var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("WeakMap",function(a){function b(a){$jscomp.owns(a,d)||$jscomp.defineProperty(a,d,{value:{}})}function c(a){var c=Object[a];c&&(Object[a]=function(a){b(a);return c(a)})}if(function(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),c=Object.seal({}),d=new a([[b,2],[c,3]]);if(2!=d.get(b)||3!=d.get(c))return!1;d.delete(b);d.set(c,4);return!d.has(b)&&4==d.get(c)}catch(l){return!1}}())return a;var d="$jscomp_hidden_"+Math.random().toString().substring(2);c("freeze");c("preventExtensions");
c("seal");var e=0,f=function(a){this.id_=(e+=Math.random()+1).toString();if(a){$jscomp.initSymbol();$jscomp.initSymbolIterator();a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};f.prototype.set=function(a,c){b(a);if(!$jscomp.owns(a,d))throw Error("WeakMap key fail: "+a);a[d][this.id_]=c;return this};f.prototype.get=function(a){return $jscomp.owns(a,d)?a[d][this.id_]:void 0};f.prototype.has=function(a){return $jscomp.owns(a,d)&&$jscomp.owns(a[d],this.id_)};f.prototype.delete=
function(a){return $jscomp.owns(a,d)&&$jscomp.owns(a[d],this.id_)?delete a[d][this.id_]:!1};return f},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(a){if(!$jscomp.ASSUME_NO_NATIVE_MAP&&function(){if(!a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),c=new a($jscomp.makeIterator([[b,"s"]]));if("s"!=c.get(b)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var d=c.entries(),e=d.next();if(e.done||e.value[0]!=b||"s"!=e.value[1])return!1;e=d.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!d.next().done?!1:!0}catch(n){return!1}}())return a;$jscomp.initSymbol();
$jscomp.initSymbolIterator();var b=new WeakMap,c=function(a){this.data_={};this.head_=f();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};c.prototype.set=function(a,b){var c=d(this,a);c.list||(c.list=this.data_[c.id]=[]);c.entry?c.entry.value=b:(c.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,value:b},c.list.push(c.entry),this.head_.previous.next=c.entry,this.head_.previous=c.entry,this.size++);return this};c.prototype.delete=
function(a){a=d(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};c.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=f();this.size=0};c.prototype.has=function(a){return!!d(this,a).entry};c.prototype.get=function(a){return(a=d(this,a).entry)&&a.value};c.prototype.entries=function(){return e(this,function(a){return[a.key,
a.value]})};c.prototype.keys=function(){return e(this,function(a){return a.key})};c.prototype.values=function(){return e(this,function(a){return a.value})};c.prototype.forEach=function(a,b){for(var c=this.entries(),d;!(d=c.next()).done;)d=d.value,a.call(b,d[1],d[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(a,c){var d=c&&typeof c;"object"==d||"function"==d?b.has(c)?d=b.get(c):(d=""+ ++g,b.set(c,d)):d="p_"+c;var e=a.data_[d];if(e&&$jscomp.owns(a.data_,d))for(a=0;a<e.length;a++){var f=
e[a];if(c!==c&&f.key!==f.key||c===f.key)return{id:d,list:e,index:a,entry:f}}return{id:d,list:e,index:-1,entry:void 0}},e=function(a,b){var c=a.head_;return $jscomp.iteratorPrototype(function(){if(c){for(;c.head!=a.head_;)c=c.previous;for(;c.next!=c.head;)return c=c.next,{done:!1,value:b(c)};c=null}return{done:!0,value:void 0}})},f=function(){var a={};return a.previous=a.next=a.head=a},g=0;return c},"es6","es3");
(function(){var a=function(a){window.console&&(window.console.error?window.console.error(a):window.console.log&&window.console.log(a))},b=function(a,b){function d(b){var c=a.parentNode;c&&(c.innerHTML='<table style="background-color: #8CE; width: 100%; height: 100%;"><tr><td align="center"><div style="display: table-cell; vertical-align: middle;"><div style="">'+b+"</div></div></td></tr></table>")}if(!window.WebGLRenderingContext)return d('This page requires a browser that supports WebGL.<br/><a href="http://get.webgl.org">Click here to upgrade your browser.</a>'),
null;(b=c(a,b))||d('It doesn\'t appear your computer can support WebGL.<br/><a href="http://get.webgl.org/troubleshooting/">Click here for more information.</a>');return b},c=function(a,b){for(var c=["webgl","experimental-webgl"],d=null,e=0;e<c.length;++e){try{d=a.getContext(c[e],b)}catch(m){}if(d)break}return d},d=function(){window!=window.top&&(document.body.className="iframe")},e=function(b,c,d,e){e=e||a;d=b.createShader(d);b.shaderSource(d,c);b.compileShader(d);return b.getShaderParameter(d,b.COMPILE_STATUS)?
d:(lastError=b.getShaderInfoLog(d),e("*** Error compiling shader '"+d+"':"+lastError),b.deleteShader(d),null)};this.createProgram=function(b,c,d,e){for(var f=b.createProgram(),g=0;g<c.length;++g)b.attachShader(f,c[g]);if(d)for(g=0;g<d.length;++g)b.bindAttribLocation(f,e?e[g]:g,d[g]);b.linkProgram(f);return b.getProgramParameter(f,b.LINK_STATUS)?f:(lastError=b.getProgramInfoLog(f),a("Error in program linking:"+lastError),b.deleteProgram(f),null)};this.createShaderFromScriptElement=function(a,b,c,d){var f=
document.getElementById(b);if(!f)throw"*** Error: unknown script element"+b;b=f.text;if(!c)if("x-shader/x-vertex"==f.type)var g=a.VERTEX_SHADER;else if("x-shader/x-fragment"==f.type)g=a.FRAGMENT_SHADER;else if(g!=a.VERTEX_SHADER&&g!=a.FRAGMENT_SHADER)throw"*** Error: unknown shader type";return e(a,b,c?c:g,d)};this.loadShader=e;this.getWebGLContext=function(a){window!=window.top&&(d(),a.width=a.clientWidth,a.height=a.clientHeight);a=b(a,{});a.getExtension("GL_OES_standard_derivatives");a.getExtension("OES_standard_derivatives");
return a};this.updateCSSIfInIFrame=d;window.requestAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a,b){return window.setTimeout(a,1E3/60)}}();window.cancelRequestAnimFrame=window.cancelCancelRequestAnimationFrame||window.webkitCancelRequestAnimationFrame||window.mozCancelRequestAnimationFrame||window.oCancelRequestAnimationFrame||window.msCancelRequestAnimationFrame||
window.clearTimeout})();function Quad(a,b,c,d,e){this.xmin=a;this.xmax=c;this.ymin=b;this.ymax=d;this.xmiddle=(a+c)/2;this.ymiddle=(b+d)/2;this.nsubquadsperside=2;this.subquadslength=this.nsubquadsperside*this.nsubquadsperside;this.subquads=Array(this.subquadslength);this.subquadsdone=!1;this.MAXCIRCLENUMBER=50;this.circlemap=Array(this.MAXCIRCLENUMBER);this.circlemapindex=0;this.errormargin=e;this.xmaxerror=this.xmax*(1+e);this.xminerror=this.xmin*(1-e);this.ymaxerror=this.ymax*(1+e);this.yminerror=this.ymin*(1-e)}
Quad.prototype.descr=function(){return"- xmin "+this.xmin+" xmax "+this.xmax+" ymin "+this.ymin+" ymax "+this.ymax};Quad.prototype.intersect=function(a){var b=a.x,c=a.y;a=a.r;var d=!1;b-a<=this.xmaxerror&&b+a>=this.xminerror&&c-a<=this.ymaxerror&&c+a>=this.yminerror&&(d=!0);return d};Quad.prototype.add=function(a){this.addwithoutcheck(a)};Quad.prototype.addwithoutcheck=function(a){this.subquadsdone?this.dispatch(a):this.insert(a)};
Quad.prototype.dispatch=function(a){for(var b=0;b<this.subquadslength;b++){var c=this.subquads[b];c.intersect(a)&&c.addwithoutcheck(a)}};Quad.prototype.ncircles=function(){return this.circlemapindex};Quad.prototype.insert=function(a){this.circlemap[this.circlemapindex]=a;this.circlemapindex+=1;this.circlemapindex==this.MAXCIRCLENUMBER&&1E-4<this.xmax-this.xmin&&this.split()};
Quad.prototype.split=function(){var a=(this.xmax-this.xmin)/this.nsubquadsperside,b=(this.ymax-this.ymin)/this.nsubquadsperside,c,d,e=this.xmin;for(c=0;c<this.nsubquadsperside;c++){var f=this.ymin;var g=c<this.nsubquadsperside-1?e+a:this.xmax;for(d=0;d<this.nsubquadsperside;d++){var h=d<this.nsubquadsperside-1?f+b:this.ymax;this.subquads[c*this.nsubquadsperside+d]=new Quad(e,f,g,h,this.errormargin);f=h}e=g}this.subquadsdone=!0;for(a=0;a<this.circlemapindex;a++)this.dispatch(this.circlemap[a]);this.circlemapindex=
0};Quad.prototype.hascollision=function(a){var b=this.errormargin;if(this.subquadsdone)for(var c=0;c<this.subquadslength;c++){var d=this.subquads[c];if(d.intersect(a)&&d.hascollision(a,b))return!0}else for(c=0;c<this.circlemapindex;c++)if(arecirclescolliding(a,this.circlemap[c],b))return!0;return!1};function QuadTree(a,b,c,d,e){this.errormargin=e;this.rootquad=new Quad(a,b,c,d,e)}QuadTree.prototype.add=function(a){this.rootquad.add(a)};
QuadTree.prototype.adds=function(a){for(var b=0;b<a.length;b++)this.add(a[b]);return this};QuadTree.prototype.iscollidingoptim=function(a){return this.rootquad.hascollision(a)};
function MetaQuadTree(a,b,c,d,e,f){this.errormargin=f;this.xmin=a;this.xmax=c;this.ymin=b;this.ymax=d;this.cellsize=e;c=Math.floor((c-a)/e);d=Math.floor((d-b)/e);this.mquadtrees=Array(c);for(var g=0;g<c;g++){this.mquadtrees[g]=Array(d);for(var h=a+e,k=b,l=0;l<d;l++){var m=k+e;this.mquadtrees[g][l]=new QuadTree(a,k,h,m,f);k=m}a=h}}
MetaQuadTree.prototype.add=function(a){for(var b=Math.floor(((a.x+a.r)*(1+this.errormargin)-this.xmin)/this.cellsize),c=Math.floor(((a.y-a.r)*(1-this.errormargin)-this.ymin)/this.cellsize),d=Math.floor(((a.y+a.r)*(1+this.errormargin)-this.ymin)/this.cellsize),e=Math.floor(((a.x-a.r)*(1-this.errormargin)-this.xmin)/this.cellsize);e<b+1;e++)for(var f=c;f<d+1;f++)this.mquadtrees[e][f].add(a)};MetaQuadTree.prototype.adds=function(a){for(var b=0;b<a.length;b++)this.add(a[b]);return this};
MetaQuadTree.prototype.iscollidingoptim=function(a){for(var b=Math.floor(((a.x+a.r)*(1+this.errormargin)-this.xmin)/this.cellsize),c=Math.floor(((a.y-a.r)*(1-this.errormargin)-this.ymin)/this.cellsize),d=Math.floor(((a.y+a.r)*(1+this.errormargin)-this.ymin)/this.cellsize),e=Math.floor(((a.x-a.r)*(1-this.errormargin)-this.xmin)/this.cellsize);e<b+1;e++)for(var f=c;f<d+1;f++){var g=this.mquadtrees[e][f].iscollidingoptim(a);if(g)return g}return!1};function mymax(a){if(1>a.length)return null;for(var b=a[0],c=1;c<a.length;c++)a[c]>b&&(b=a[c]);return b}function mymin(a){if(1>a.length)return null;for(var b=a[0],c=1;c<a.length;c++)a[c]<b&&(b=a[c]);return b}var randomseed=0;function initrandomseed(a){randomseed=a}function myrandom(){var a=1E4*Math.sin(randomseed++);return a-Math.floor(a)}function rand(a,b){return myrandom()*(b-a)+a}function randitem(a){return a[Math.floor(rand(0,a.length))]}function lcircular(a,b){return a[b%a.length]}
function lconcat(a,b){return a.concat(b)}function lrepeat(a,b){var c=[],d;for(d=0;d<b;d++)c.push(a);return c}function sample(a,b,c){return a+(b-a)*c}function abscissa(a,b,c){return c>b?b:c<a||a==b?a:(c-a)/(b-a)}function samples(a,b,c){var d=[],e;for(e=0;e<c;e++)d.push(sample(a,b,e/c));return d}function lfill(a,b){for(var c=[],d=0;d<b;d++)c.push(a);return c}function llast(a){return a[a.length-1]}function lfirst(a){return a[0]}function lsum(a){for(var b=0,c=0;c<a.length;c++)b+=a[c];return b}
function lreverse(a){for(var b=[],c=a.length-1;-1<c;--c)b.push(a[c]);return b}function randfluctuate(a,b){return rand(a*(1-b),a*(1+b))}function lrandfluctuate(a,b){for(var c=[],d=0;d<a.length;d++)c.push(randfluctuate(a[d],b));return c}function lgeo(a,b,c,d){for(var e=[1],f=0;f<d-1;f++)e.push(llast(e)*c);for(f=0;f<d;f++)e[f]=1-e[f];c=lfirst(e);var g=llast(e);for(f=0;f<d;f++){var h=abscissa(c,g,e[f]);e[f]=sample(a,b,h)}return e}
function rcircular(a,b,c){var d=c,e=b-a;c<a?(d=Math.floor((c-b)/e),d=b+(c-b-d*e)):c>b&&(d=Math.floor((c-a)/e),d=a+(c-a-d*e));return d}function rtrim(a,b,c){return c>=b?b:c<=a?a:c};function Point(a,b){this.x=a;this.y=b}function Circle(a,b,c){this.x=a;this.y=b;this.r=c;this.width=2*c;this.height=2*c;this.radius=c;this.descr=function(){return"x "+this.x+" y "+this.y+" r "+this.r}}function circle(a,b,c){return new Circle(a,b,c)}function ccenter(a){return new Point(a.x,a.y)}function cscale(a,b){return new Circle(a.x,a.y,a.r*b)}function rectangle(a,b,c,d){return{x:a,y:b,width:c,height:d}}
function vrotate(a,b){var c=Math.sin(b);b=Math.cos(b);return $V([a.e(1)*b-a.e(2)*c,a.e(1)*c+a.e(2)*b])}function adjcircle(a,b,c){var d=$V([a.x,a.y]);a=vrotate($V([a.r+b,0]),c);d=d.add(a);return new Circle(d.e(1),d.e(2),b)}
function circles2tangent2(a,b,c,d,e,f){var g=a.r,h=c.x,k=c.y;c=c.r;a=$V([a.x-h,a.y-k]);var l=a.modulus();isens=1;if("IN"==b||"IN"==d)isens=-1;b=g+isens*e;d=c+e;b=(l*l-b*b+d*d)/(2*d*l);if(-1>b||1<b)return console.log("cosv ",b),[];f=a.rotate(Math.acos(b)*f,$V([0,0])).toUnitVector().multiply(d);h=$V([h,k]).add(f);return[new circle(h.e(1),h.e(2),e)]}
function circles2tangent(a,b,c,d,e,f){var g=a.r,h=c.x,k=c.y;c=c.r;a=$V([a.x-h,a.y-k]);var l=a.modulus();isens=1;if("IN"==b||"IN"==d)isens=-1;b=g+isens*e;d=c+e;b=(l*l-b*b+d*d)/(2*d*l);if(-1>b||1<b)b=-1>b?-1:1;f=a.rotate(Math.acos(b)*f,$V([0,0])).toUnitVector().multiply(d);h=$V([h,k]).add(f);return new Circle(h.e(1),h.e(2),e)}
function circles2tangentoptim(a,b,c,d){var e=b.x,f=b.y,g=a.x-e,h=a.y-f,k=Math.sqrt(g*g+h*h);a=a.r+1*c;b=b.r+c;a=(k*k-a*a+b*b)/(2*b*k);if(-1>a||1<a)a=-1>a?-1:1;d*=Math.sqrt(1-a*a);return[e+(a*g-d*h)*b/k,f+(d*g+a*h)*b/k,c]}function circleviewbox(a){return[a.x-a.r,a.y-a.r,a.x+a.r,a.y+a.r]}function mergeviewboxes(a,b){if(0>=b.length)return a;var c=a[1],d=a[2],e=a[3],f=b[1],g=b[2],h=b[3];a=mymin([a[0],b[0]]);c=mymin([c,f]);d=mymax([d,g]);e=mymax([e,h]);return[a,c,d,e]}
function expandviewbox(a,b){var c=a[0],d=a[1],e=a[2],f=a[3];a=(e-c)*b;b*=f-d;c=(c+e)/2;d=(d+f)/2;return[c-a/2,d-b/2,c+a/2,d+b/2]}function centerviewbox(a,b){var c=a[1],d=a[3];a=mymax([b[0]-a[0],a[2]-b[0]]);c=mymax([b[1]-c,d-b[1]]);return[b[0]-a,b[1]-c,b[0]+a,b[1]+c]}function squareviewbox(a){var b=a[0],c=a[1],d=a[2],e=a[3];a=(d+b)/2;var f=(e+c)/2;b=mymax([d-b,e-c])/2;return[a-b,f-b,a+b,f+b]}
function ratioviewbox(a,b){var c=a[0],d=a[1],e=a[2],f=a[3];a=e-c;var g=f-d;c=(e+c)/2;d=(f+d)/2;1<b?a*=b:g/=b;return[c-a/2,d-g/2,c+a/2,d+a/2]}function convertviewboxwidthheight(a){var b=a[0],c=a[1];return[b,c,a[2]-b,a[3]-c]}function arecirclescolliding(a,b){var c=a.x-b.x,d=a.y-b.y;a=a.radius+b.radius;return-1E-6>c*c+d*d-a*a}function computecirclesviewbox(a){for(var b=circleviewbox(a[0]),c=1;c<a.length;++c)b=mergeviewboxes(b,circleviewbox(a[c]));return b}
function checkcirclescollision(a,b,c){for(var d=0;d<a.length;++d)if(arecirclescolliding(b,a[d],c))return!0;return!1}function checkcollisionquadtree(a,b){return a.iscollidingoptim(b)}function collidings(a,b,c){return a.collidings(b,c)}function insertquadtree(a,b){a.add(b)}function circlepoints(a,b,c){var d=[],e=$V([a.x,a.y]);a=$V([a.r,0]);b=samples(0,6.283138,b);var f;for(f=0;f<b.length;f++){var g=e.add(vrotate(a,b[f]+c));d.push(new Point(g.e(1),g.e(2)))}return d}
function linepoints(a,b,c){var d=[],e=samples(a.x,b.x,c);a=samples(a.y,b.y,c);for(b=0;b<c;b++)d.push(new Point(e[b],a[b]));return d}function linecircles(a,b,c){var d=[],e=linepoints(a,b,c);a=$V([a.x-b.x,a.y-b.y]).modulus()/c;for(b=0;b<e.length;b++)c=e[b],d.push(new Circle(c.x,c.y,a));return d}function dist2(a,b){var c=a.x-b.x;a=a.y-b.y;return c*c+a*a}function arecircletangent(a,b){var c=(a.x-b.x)*(a.x-b.x)+(a.y-b.y)*(a.y-b.y);a=(a.r+b.r)*(a.r+b.r);return 1E-5>(c-a)*(c-a)/a?!0:!1};function drawcircle(a,b,c,d){var e=a.coordindex;a.coords[e+0]=b-2*d;a.coords[e+1]=c-d;a.coords[e+2]=b;a.coords[e+3]=c;a.coords[e+4]=d;e+=5;a.coords[e+0]=b+2*d;a.coords[e+1]=c-d;a.coords[e+2]=b;a.coords[e+3]=c;a.coords[e+4]=d;e+=5;a.coords[e+0]=b;a.coords[e+1]=c+2*d;a.coords[e+2]=b;a.coords[e+3]=c;a.coords[e+4]=d;a.coordindex=e+5;a.nnewcircles+=1}
function computeViewPortMatrix(a,b){var c=b[0],d=b[1],e=b[2],f=b[3],g=e-c;b=f-d;a=a.canvasratio;var h=2/g,k=2/b;c=-((c+e)/2)*h;1>a&&(c+=g/2*h*(a-1));d=-((d+f)/2)*k;1<a&&(d+=b/2*k*(1-1/a));h!=k&&console.log("ERROR: scale x",h,"!= scaley",k);return new Float32Array([h,0,0,0,0,h,0,0,0,0,1,0,c,d,0,1])}
function computeScreenPortMatrix(a,b){var c=b[0],d=b[1],e=b[2],f=b[3],g=e-c;b=f-d;var h=a.canvasratio,k=a.canvaswidth/g,l=a.canvasheight/b;c=a.canvaswidth/2-(c+e)/2*k;1>h&&(c+=g/2*k*(h-1));a=a.canvasheight/2-(d+f)/2*l;1<h&&(a+=b/2*l*(1-1/h));return new Float32Array([k,0,0,0,0,l,0,0,0,0,1,0,c,a,0,1])}
function initcanvas(a){document.getElementById(a).innerHTML='<canvas id = "canvas'+a+'"  />';canvas=document.getElementById("canvas"+a);if(gl=getWebGLContext(canvas))vertexShader=loadShader(gl,"attribute vec2  aVertexPosition;\nattribute vec3  aCircleDef;\nuniform   mat4  uModelViewMatrix;\nuniform   mat4  uScreenViewMatrix;\nuniform   float uAlpha;\nvarying   vec2  vCircleCenter;\nvarying   float vCircleRadius;\nvarying   float vAlpha;\nvoid main(void) {\n   gl_Position  = uModelViewMatrix * vec4(aVertexPosition, 0.0, 1.0);\n   vCircleCenter   = vec2(uScreenViewMatrix * vec4(aCircleDef[0], aCircleDef[1], 0.0,1.0));\n   vCircleRadius   = uScreenViewMatrix[0][0] * aCircleDef[2];\n   vAlpha          = uAlpha;\n}",gl.VERTEX_SHADER),
fragmentShader=loadShader(gl,"#ifdef GL_OES_standard_derivatives\n#extension GL_OES_standard_derivatives : enable\n#endif\nprecision mediump float;\nvarying vec2  vCircleCenter;\nvarying float vCircleRadius;\nvarying float vAlpha;\nvoid main(void) {\nvec2 cxy = vec2(gl_FragCoord) + vec2(0.5,0.5) - vCircleCenter;\nfloat alpha = 1.0;\nfloat r =  (dot(cxy, cxy))/(vCircleRadius * vCircleRadius);\n#ifdef GL_OES_standard_derivatives\n float delta = fwidth(r);\n alpha = 1.0 - smoothstep(1.0 - delta, 1.0 + delta, r);\n#endif\n   gl_FragColor = vec4(0.0,0.0,0.0,1.0) * alpha * vAlpha;\n}",
gl.FRAGMENT_SHADER),program=createProgram(gl,[vertexShader,fragmentShader]),gl.useProgram(program),gl.modelviewmatrixloc=gl.getUniformLocation(program,"uModelViewMatrix"),gl.alpha=gl.getUniformLocation(program,"uAlpha"),gl.screenviewmatrixloc=gl.getUniformLocation(program,"uScreenViewMatrix"),gl.vertexposloc=gl.getAttribLocation(program,"aVertexPosition"),gl.circledef=gl.getAttribLocation(program,"aCircleDef"),gl.enableVertexAttribArray(gl.vertexposloc),gl.enableVertexAttribArray(gl.circledef),gl.batchs=
[],gl.viewbox0=[-1,-1,1,1],a=function(){var a=window.innerWidth,c=window.innerHeight,d=c>a?c:a;canvas.width=d;canvas.height=d;gl.canvaswidth=d;gl.canvasheight=d;d=a/c;console.log("canvas.innerWidth",a,"canvas.innerHeight",c);gl.canvasratio=d;gl.viewport(0,0,gl.canvaswidth,gl.canvasheight);resetviewbox(gl)},window.onresize=a,a()}
function createnewbatch(a){var b={};b.bcoords=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,b.bcoords);a.bufferData(a.ARRAY_BUFFER,new Float32Array(a.coords),a.STATIC_DRAW);b.ncircles=a.nnewcircles;b.alpha=0;b.alphaincr=.05;return b}function redrawbatch(a,b){a.bindBuffer(a.ARRAY_BUFFER,b.bcoords);a.vertexAttribPointer(a.vertexposloc,2,a.FLOAT,!1,20,0);a.vertexAttribPointer(a.circledef,3,a.FLOAT,!1,20,8);a.drawArrays(a.TRIANGLES,0,3*b.ncircles);b.alpha+=b.alphaincr}
function resetviewbox(a){a.clear(a.COLOR_BUFFER_BIT|a.DEPTH_BUFFER_BIT);a.blendFunc(a.SRC_ALPHA,a.ONE_MINUS_SRC_ALPHA);a.enable(a.BLEND);a.disable(a.DEPTH_TEST);var b=computeViewPortMatrix(a,a.viewbox0);a.uniformMatrix4fv(a.modelviewmatrixloc,!1,b);b=computeScreenPortMatrix(a,a.viewbox0);a.uniformMatrix4fv(a.screenviewmatrixloc,!1,b);for(var c=b=0;c<a.batchs.length;c++){var d=a.batchs[c];a.uniform1f(a.alpha,1>d.alpha?d.alpha:1);redrawbatch(a,d);b+=d.ncircles}console.log("ncircles",b)}
function startanim(a){requestAnimFrame(a)}function relaunchloop(a,b){a&&requestAnimFrame(b)}function bindcanvas(a,b,c,d){}function myhsla(a,b,c,d){return(new Color).hsla(a,b,c,d)};function plug(a,b,c){return{c1:a,c2:b,side:c}}
function bpatternpackingalternate(a,b){this.lastindex=1;this.front=Array(2E4);this.frontbackindex=this.frontfrontindex=1E4;var c=0;for(c=0;c<a.length;c++)this.front[this.frontbackindex]=a[c],this.frontbackindex+=1;this.minsize=.01;this.maxsize=.5;this.initratios=function(a){this.mratios=a;this.mmap=new Map;this.mratioindex=0;var b;for(b=0;b<a.length-1;b++){var c=a[b],d=a[b+1],h=c/d,k=d/c;this.mmap.set(this.ratioround(c),d);this.mmap.set(this.ratioround(h),d);this.mmap.set(this.ratioround(k),d)}};
this.ratioround=function(a){return Math.round(a*Math.pow(10,6))/Math.pow(10,6)};this.initratios(b);this.checkpreviousratiosmap=function(a){a=this.ratioround(a);return self.mmap.has(a)?self.mmap.get(a):null};this.radiusf=function(a,b){a/=b;1<a&&(a=1/a);a=this.ratioround(a);if(this.mmap.has(a))var c=this.mmap.get(a);else c=lcircular(this.mratios,this.mratioindex),this.mmap.set(a,c),this.mratioindex+=1;return c*b};this.getlastplug=function(){var a=null;this.frontfrontindex!=this.frontbackindex&&(a=this.front[this.frontfrontindex],
this.frontfrontindex+=1);return a};this.updatewithnewnode=function(a,b,c,g){this.frontfrontindex+=-1;this.front[this.frontfrontindex]=plug(g,a,-c);this.frontbackindex+=1;this.front[this.frontbackindex]=plug(g,b,c)};this.updateresult=function(a,b){a.push(b);return a};this.iter=function(a,b){this.result=Array(b);this.resultindex=0;var c;for(c=0;c<b;c++){var d=this.getlastplug();if(d){var e=d.c1,k=d.c2;d=d.side;var l=this.radiusf(e.r,k.r);l>this.minsize&&l<this.maxsize&&(l=circles2tangentoptim(e,k,l,
d),l=new Circle(l[0],l[1],l[2]),checkcollisionquadtree(a,l)||(insertquadtree(a,l),this.updatewithnewnode(e,k,d,l),this.result[this.resultindex]=l,this.resultindex+=1))}}return[this.result,this.resultindex]}};var canvasname="bloganim",colgrid=null,quadtree=null,lastpatternid=0,patterns=[],canvas=null,gl=null,ratios=[.2728331728246218,.5071356634176968,.4290950612300518,.8006940934810294,.2656291356615858,.4288830642722934,.23766122443492582,.3721990777981463,.5499005534452854,.17860175491245545,.7596948136387834,.1907328270332575,.6466239479587524,.8086933427530776,.709011650974402,.35881792677511365,.6528953093350377,.21146399397936835,.07534681124396007,.35385657723706987,.26749362343339883,.7653290451342841,
.8852615719126824,.5912391364533637,.9561663716827362,.28820887174839566,.9265074752860272,.811137132258684,.7817818717014892,.4079176869280253];ratios=ratios.map(function(a){return sample(.5,1.2,a)});var viewbox0=null,errormargin=1E-5;function rootseedratio(a,b){return plug(new Circle(0,-a*b,a*b),new Circle(0,b,b),-1)}
function context(){function a(){d=3E5>d?Math.floor(1.03*d):0;if(3E5>b&&0<patterns.length){var e=patterns[0].iter(quadtree,d),f=e[0];e=e[1];if(0<e){gl.coords=Array(15*e);gl.coordindex=0;for(var g=gl.nnewcircles=0;g<e;g++){var h=f[g],k=h.r-.01;0<k&&drawcircle(gl,h.x,h.y,k)}gl.batchs.push(createnewbatch(gl))}}b+=d;viewbox0=expandviewbox(viewbox0,1);gl.viewbox0=squareviewbox(expandviewbox(viewbox0,1));resetviewbox(gl);3E5<=b&&(f=(new Date).getTime()-c,console.log("iter duration ",f),console.log("xmin",
0,"ymin",0,"xmax",0,"ymax",0));return relaunchloop(6E5>b,a)}initrandomseed(0);initcanvas(canvasname);var b=0,c=(new Date).getTime();0==patterns.length&&(seed=rootseedratio(ratios[0],.1),patterns.push(new bpatternpackingalternate([seed],ratios)));quadtree=new MetaQuadTree(-200,-200,200,200,2,errormargin);viewbox0=mergeviewboxes(circleviewbox(new Circle(-5,0,30)),circleviewbox(new Circle(0,0,1)));console.log("init viewbox0",viewbox0);var d=1E3;return a}startanim(context());

