var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,e,d){b!=Array.prototype&&b!=Object.prototype&&(b[e]=d.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var b=0;return function(e){return $jscomp.SYMBOL_PREFIX+(e||"")+b++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(b){var e=0;return $jscomp.iteratorPrototype(function(){return e<b.length?{done:!1,value:b[e++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};$jscomp.makeIterator=function(b){$jscomp.initSymbolIterator();var e=b[Symbol.iterator];return e?e.call(b):$jscomp.arrayIterator(b)};$jscomp.owns=function(b,e){return Object.prototype.hasOwnProperty.call(b,e)};
$jscomp.polyfill=function(b,e,d,a){if(e){d=$jscomp.global;b=b.split(".");for(a=0;a<b.length-1;a++){var g=b[a];g in d||(d[g]={});d=d[g]}b=b[b.length-1];a=d[b];e=e(a);e!=a&&null!=e&&$jscomp.defineProperty(d,b,{configurable:!0,writable:!0,value:e})}};
$jscomp.polyfill("WeakMap",function(b){function e(b){$jscomp.owns(b,a)||$jscomp.defineProperty(b,a,{value:{}})}function d(a){var c=Object[a];c&&(Object[a]=function(a){e(a);return c(a)})}if(function(){if(!b||!Object.seal)return!1;try{var a=Object.seal({}),c=Object.seal({}),h=new b([[a,2],[c,3]]);if(2!=h.get(a)||3!=h.get(c))return!1;h.delete(a);h.set(c,4);return!h.has(a)&&4==h.get(c)}catch(f){return!1}}())return b;var a="$jscomp_hidden_"+Math.random().toString().substring(2);d("freeze");d("preventExtensions");
d("seal");var g=0,k=function(a){this.id_=(g+=Math.random()+1).toString();if(a){$jscomp.initSymbol();$jscomp.initSymbolIterator();a=$jscomp.makeIterator(a);for(var c;!(c=a.next()).done;)c=c.value,this.set(c[0],c[1])}};k.prototype.set=function(b,c){e(b);if(!$jscomp.owns(b,a))throw Error("WeakMap key fail: "+b);b[a][this.id_]=c;return this};k.prototype.get=function(b){return $jscomp.owns(b,a)?b[a][this.id_]:void 0};k.prototype.has=function(b){return $jscomp.owns(b,a)&&$jscomp.owns(b[a],this.id_)};k.prototype.delete=
function(b){return $jscomp.owns(b,a)&&$jscomp.owns(b[a],this.id_)?delete b[a][this.id_]:!1};return k},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(b){if(!$jscomp.ASSUME_NO_NATIVE_MAP&&function(){if(!b||!b.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),a=new b($jscomp.makeIterator([[c,"s"]]));if("s"!=a.get(c)||1!=a.size||a.get({x:4})||a.set({x:4},"t")!=a||2!=a.size)return!1;var f=a.entries(),d=f.next();if(d.done||d.value[0]!=c||"s"!=d.value[1])return!1;d=f.next();return d.done||4!=d.value[0].x||"t"!=d.value[1]||!f.next().done?!1:!0}catch(m){return!1}}())return b;$jscomp.initSymbol();
$jscomp.initSymbolIterator();var e=new WeakMap,d=function(a){this.data_={};this.head_=k();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var c;!(c=a.next()).done;)c=c.value,this.set(c[0],c[1])}};d.prototype.set=function(c,b){var f=a(this,c);f.list||(f.list=this.data_[f.id]=[]);f.entry?f.entry.value=b:(f.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:c,value:b},f.list.push(f.entry),this.head_.previous.next=f.entry,this.head_.previous=f.entry,this.size++);return this};d.prototype.delete=
function(c){c=a(this,c);return c.entry&&c.list?(c.list.splice(c.index,1),c.list.length||delete this.data_[c.id],c.entry.previous.next=c.entry.next,c.entry.next.previous=c.entry.previous,c.entry.head=null,this.size--,!0):!1};d.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=k();this.size=0};d.prototype.has=function(c){return!!a(this,c).entry};d.prototype.get=function(c){return(c=a(this,c).entry)&&c.value};d.prototype.entries=function(){return g(this,function(a){return[a.key,
a.value]})};d.prototype.keys=function(){return g(this,function(a){return a.key})};d.prototype.values=function(){return g(this,function(a){return a.value})};d.prototype.forEach=function(a,b){for(var c=this.entries(),d;!(d=c.next()).done;)d=d.value,a.call(b,d[1],d[0],this)};d.prototype[Symbol.iterator]=d.prototype.entries;var a=function(a,b){var c=b&&typeof b;"object"==c||"function"==c?e.has(b)?c=e.get(b):(c=""+ ++l,e.set(b,c)):c="p_"+b;var d=a.data_[c];if(d&&$jscomp.owns(a.data_,c))for(a=0;a<d.length;a++){var g=
d[a];if(b!==b&&g.key!==g.key||b===g.key)return{id:c,list:d,index:a,entry:g}}return{id:c,list:d,index:-1,entry:void 0}},g=function(a,b){var c=a.head_;return $jscomp.iteratorPrototype(function(){if(c){for(;c.head!=a.head_;)c=c.previous;for(;c.next!=c.head;)return c=c.next,{done:!1,value:b(c)};c=null}return{done:!0,value:void 0}})},k=function(){var a={};return a.previous=a.next=a.head=a},l=0;return d},"es6","es3");function plug(b,e,d){return{c1:b,c2:e,side:d}}
function bpatternpackingalternate(b,e){this.lastindex=1;this.front=Array(2E4);this.frontbackindex=this.frontfrontindex=1E4;var d=0;for(d=0;d<b.length;d++)this.front[this.frontbackindex]=b[d],this.frontbackindex+=1;this.minsize=.01;this.maxsize=.5;this.initratios=function(a){this.mratios=a;this.mmap=new Map;this.mratioindex=0;var b;for(b=0;b<a.length-1;b++){var d=a[b],e=a[b+1],c=d/e,h=e/d;this.mmap.set(this.ratioround(d),e);this.mmap.set(this.ratioround(c),e);this.mmap.set(this.ratioround(h),e)}};
this.ratioround=function(a){return Math.round(a*Math.pow(10,6))/Math.pow(10,6)};this.initratios(e);this.checkpreviousratiosmap=function(a){a=this.ratioround(a);return self.mmap.has(a)?self.mmap.get(a):null};this.radiusf=function(a,b){a/=b;1<a&&(a=1/a);a=this.ratioround(a);if(this.mmap.has(a))var d=this.mmap.get(a);else d=lcircular(this.mratios,this.mratioindex),this.mmap.set(a,d),this.mratioindex+=1;return d*b};this.getlastplug=function(){var a=null;this.frontfrontindex!=this.frontbackindex&&(a=this.front[this.frontfrontindex],
this.frontfrontindex+=1);return a};this.updatewithnewnode=function(a,b,d,e){this.frontfrontindex+=-1;this.front[this.frontfrontindex]=plug(e,a,-d);this.frontbackindex+=1;this.front[this.frontbackindex]=plug(e,b,d)};this.updateresult=function(a,b){a.push(b);return a};this.iter=function(a,b){this.result=Array(b);this.resultindex=0;var d;for(d=0;d<b;d++){var e=this.getlastplug();if(e){var c=e.c1,g=e.c2;e=e.side;var f=this.radiusf(c.r,g.r);f>this.minsize&&f<this.maxsize&&(f=circles2tangentoptim(c,g,f,
e),f=new Circle(f[0],f[1],f[2]),checkcollisionquadtree(a,f)||(insertquadtree(a,f),this.updatewithnewnode(c,g,e,f),this.result[this.resultindex]=f,this.resultindex+=1))}}return[this.result,this.resultindex]}};
