var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,f,e){a!=Array.prototype&&a!=Object.prototype&&(a[f]=e.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(f){return $jscomp.SYMBOL_PREFIX+(f||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var f=0;return $jscomp.iteratorPrototype(function(){return f<a.length?{done:!1,value:a[f++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var f=a[Symbol.iterator];return f?f.call(a):$jscomp.arrayIterator(a)};$jscomp.owns=function(a,f){return Object.prototype.hasOwnProperty.call(a,f)};
$jscomp.polyfill=function(a,f,e,c){if(f){e=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var d=a[c];d in e||(e[d]={});e=e[d]}a=a[a.length-1];c=e[a];f=f(c);f!=c&&null!=f&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:f})}};
$jscomp.polyfill("WeakMap",function(a){function f(a){$jscomp.owns(a,c)||$jscomp.defineProperty(a,c,{value:{}})}function e(a){var b=Object[a];b&&(Object[a]=function(a){f(a);return b(a)})}if(function(){if(!a||!Object.seal)return!1;try{var c=Object.seal({}),b=Object.seal({}),k=new a([[c,2],[b,3]]);if(2!=k.get(c)||3!=k.get(b))return!1;k.delete(c);k.set(b,4);return!k.has(c)&&4==k.get(b)}catch(g){return!1}}())return a;var c="$jscomp_hidden_"+Math.random().toString().substring(2);e("freeze");e("preventExtensions");
e("seal");var d=0,l=function(a){this.id_=(d+=Math.random()+1).toString();if(a){$jscomp.initSymbol();$jscomp.initSymbolIterator();a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};l.prototype.set=function(a,b){f(a);if(!$jscomp.owns(a,c))throw Error("WeakMap key fail: "+a);a[c][this.id_]=b;return this};l.prototype.get=function(a){return $jscomp.owns(a,c)?a[c][this.id_]:void 0};l.prototype.has=function(a){return $jscomp.owns(a,c)&&$jscomp.owns(a[c],this.id_)};l.prototype.delete=
function(a){return $jscomp.owns(a,c)&&$jscomp.owns(a[c],this.id_)?delete a[c][this.id_]:!1};return l},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(a){if(!$jscomp.ASSUME_NO_NATIVE_MAP&&function(){if(!a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),c=new a($jscomp.makeIterator([[b,"s"]]));if("s"!=c.get(b)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var g=c.entries(),d=g.next();if(d.done||d.value[0]!=b||"s"!=d.value[1])return!1;d=g.next();return d.done||4!=d.value[0].x||"t"!=d.value[1]||!g.next().done?!1:!0}catch(n){return!1}}())return a;$jscomp.initSymbol();
$jscomp.initSymbolIterator();var f=new WeakMap,e=function(b){this.data_={};this.head_=l();this.size=0;if(b){b=$jscomp.makeIterator(b);for(var a;!(a=b.next()).done;)a=a.value,this.set(a[0],a[1])}};e.prototype.set=function(a,d){var b=c(this,a);b.list||(b.list=this.data_[b.id]=[]);b.entry?b.entry.value=d:(b.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,value:d},b.list.push(b.entry),this.head_.previous.next=b.entry,this.head_.previous=b.entry,this.size++);return this};e.prototype.delete=
function(b){b=c(this,b);return b.entry&&b.list?(b.list.splice(b.index,1),b.list.length||delete this.data_[b.id],b.entry.previous.next=b.entry.next,b.entry.next.previous=b.entry.previous,b.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=l();this.size=0};e.prototype.has=function(b){return!!c(this,b).entry};e.prototype.get=function(b){return(b=c(this,b).entry)&&b.value};e.prototype.entries=function(){return d(this,function(b){return[b.key,
b.value]})};e.prototype.keys=function(){return d(this,function(b){return b.key})};e.prototype.values=function(){return d(this,function(b){return b.value})};e.prototype.forEach=function(b,a){for(var c=this.entries(),d;!(d=c.next()).done;)d=d.value,b.call(a,d[1],d[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var c=function(b,a){var c=a&&typeof a;"object"==c||"function"==c?f.has(a)?c=f.get(a):(c=""+ ++h,f.set(a,c)):c="p_"+a;var d=b.data_[c];if(d&&$jscomp.owns(b.data_,c))for(b=0;b<d.length;b++){var e=
d[b];if(a!==a&&e.key!==e.key||a===e.key)return{id:c,list:d,index:b,entry:e}}return{id:c,list:d,index:-1,entry:void 0}},d=function(a,c){var b=a.head_;return $jscomp.iteratorPrototype(function(){if(b){for(;b.head!=a.head_;)b=b.previous;for(;b.next!=b.head;)return b=b.next,{done:!1,value:c(b)};b=null}return{done:!0,value:void 0}})},l=function(){var a={};return a.previous=a.next=a.head=a},h=0;return e},"es6","es3");
function bpattern(a,f){this.lastindex=1;this.nodes=f;this.side=a;this.iter=function(a,c){return[]}}function plug(a,f,e){return{c1:a,c2:f,side:e}}
function bpatternparrot(a){this.lastindex=1;this.nodes=a;this.front=[plug(a[0],a[1],1),plug(a[0],a[1],-1)];this.nsubiter=10;this.nsubpattern=100;this.iter=function(a,e){result=[];for(var c=0;c<this.nsubpattern;c++){var d=this.nsubiter,f=this.front.slice(0,d);this.front=this.front.slice(d);for(d=0;d<f.length;++d){var h=f[d],b=h.c1,k=h.c2;h=h.side;var g=.99*mymax([b.r,k.r]);if(.05<g&&(g=circles2tangent(b,"OUT",k,"OUT",g,h),!checkcollisionquadtree(a,g))){this.nodes.push(g);insertquadtree(a,g);var m=
myhsla((this.nodes.length+10)%6E4/6E4,1,.5,1);drawcircle(e,circle(g.x,g.y,g.r),m);this.front=b=[plug(g,b,-h)].concat(this.front.slice(0));this.front=b=[plug(k,g,-h)].concat(this.front.slice(0));result.push(g)}}}return result}}
function bpatternpacking(a){this.lastindex=1;this.nodes=a;this.front=[plug(a[0],a[1],1),plug(a[0],a[1],-1)];this.nsubiter=1E3;this.iter=function(a,e){result=[];var c;for(c=0;c<this.nsubiter;c++)if(0<this.front.length){var d=this.front[0];this.front=this.front.slice(1);var f=d.c1,h=d.c2;d=d.side;var b=mymax([f.r,h.r])*rand(.9,.97);if(.3<b&&(b=circles2tangent(f,"OUT",h,"OUT",b,d),!checkcollisionquadtree(a,b))){this.nodes.push(b);a.insert(b);var k=myhsla((this.nodes.length+10)%6E4/6E4,1,.5,1);drawcircle(e,
circle(b.x,b.y,b.r),k);this.front.push(plug(b,f,-d));this.front.push(plug(h,b,-d));this.front.push(plug(b,f,d));this.front.push(plug(h,b,d));result.push(b)}}return result}}
function bpatternpackingalternate(a,f){this.lastindex=1;this.front=Array(2E4);this.frontbackindex=this.frontfrontindex=1E4;var e=0;for(e=0;e<a.length;e++)this.front[this.frontbackindex]=a[e],this.frontbackindex+=1;this.minsize=.01;this.maxsize=.5;this.initratios=function(a){this.mratios=a;this.mmap=new Map;this.mratioindex=0;var c;for(c=0;c<a.length-1;c++){var e=a[c],f=a[c+1],b=e/f,k=f/e;this.mmap.set(this.ratioround(e),f);this.mmap.set(this.ratioround(b),f);this.mmap.set(this.ratioround(k),f)}};
this.ratioround=function(a){return Math.round(a*Math.pow(10,6))/Math.pow(10,6)};this.initratios(f);this.checkpreviousratiosmap=function(a){a=this.ratioround(a);return self.mmap.has(a)?self.mmap.get(a):null};this.radiusf=function(a,d){a/=d;1<a&&(a=1/a);a=this.ratioround(a);if(this.mmap.has(a))var c=this.mmap.get(a);else c=lcircular(this.mratios,this.mratioindex),this.mmap.set(a,c),this.mratioindex+=1;return c*d};this.getlastplug=function(){var a=null;this.frontfrontindex!=this.frontbackindex&&(a=this.front[this.frontfrontindex],
this.frontfrontindex+=1);return a};this.updatewithnewnode=function(a,d,e,f){this.frontfrontindex+=-1;this.front[this.frontfrontindex]=plug(f,a,-e);this.frontbackindex+=1;this.front[this.frontbackindex]=plug(f,d,e)};this.updateresult=function(a,d){a.push(d);return a};this.iter=function(a,d){this.result=Array(d);this.resultindex=0;var c;for(c=0;c<d;c++){var e=this.getlastplug();if(e){var b=e.c1,f=e.c2;e=e.side;var g=this.radiusf(b.r,f.r);g>this.minsize&&g<this.maxsize&&(g=circles2tangentoptim(b,f,g,
e),g=new Circle(g[0],g[1],g[2]),checkcollisionquadtree(a,g)||(insertquadtree(a,g),this.updatewithnewnode(b,f,e,g),this.result[this.resultindex]=g,this.resultindex+=1))}}return[this.result,this.resultindex]}};
